Abdicoder123/african_queen_kitchen

app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/views/home/index.html.erb
config/routes.rb
test/controllers/home_controller_test.rb

Created basic homepage controller and view

feature added homepage controller and view

---

app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/views/home/index.html.erb
config/routes.rb
test/controllers/home_controller_test.rb

Reverts Abdicoder123/group_project#2

Revert "feature added homepage controller and view"

---

app/controllers/home_controller.rb
app/helpers/home_helper.rb
app/views/home/index.html.erb
config/routes.rb
db/schema.rb
test/controllers/home_controller_test.rb

- I generated a home controller. I added an index.html.erb view with a simple h1 tag. Then I updated routes to route the home page. Then I ran rubocop and ran a db migrate to pass checks.

feature added homepage

---

Gemfile
Gemfile.lock

- I added a bootstrap gem and a scss gem for styling purposes. [ticket](https://trello.com/c/MZtLzvis/47-add-bootstrap-gem)

added bootstrap and scss gems

---

app/assets/stylesheets/application.scss
app/views/layouts/_nav.html.erb
app/views/layouts/application.html.erb

- I added a nav bar and used bootstrap to style it. The titles on the bar are placeholders but I think they're pretty close to what we want in the end. [ticket](https://trello.com/c/gpUNdYfE/43-add-navbar)

added navbar and styled

---

Gemfile
Gemfile.lock
config/database.yml
db/schema.rb

- Adding postgresql as the default database.
- Added pg gem
- Reconfigured the host to localhost in database.yml
- Updated /.github/workflow/ci.yml to install postgresql instead of sqlite
- After pulling, run rails db:create
- After that run db:migrate
- It should create the african_queen_kitchen_development and african_queen_kitchen_test in postico

Feature: add postgresql to app

---

app/models/menu.rb
db/migrate/20250115170125_create_menus.rb
db/schema.rb
test/fixtures/menus.yml
test/models/menu_test.rb

- Generated the menu model with the id and name columns. This is the ticket it's handling, https://trello.com/c/TVwaNgTB

Feature: Generate menu model

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/home.scss
app/views/home/index.html.erb
app/views/layouts/application.html.erb

I added a grid styling layout similar to the inspirations sites onto the homepage with placeholders. The [ticket](https://trello.com/c/IOmY6aju/15-style-homepage)
-Added another scss stylesheet
-Added grid styling to home index page
-Added a container div in layouts/app so everything is centered

added a home layout

---

.github/workflows/ci.yml
app/models/order.rb
config/database.yml
db/migrate/20250117164226_create_orders.rb
db/schema.rb
test/fixtures/orders.yml
test/models/order_test.rb

- I generated the order model with the established parameters
- Generated the order model with its columns
- run db:migrate

generated order model

---

.github/workflows/ci.yml
app/models/order.rb
config/database.yml
db/migrate/20250117164226_create_orders.rb
db/schema.rb
test/fixtures/orders.yml
test/models/order_test.rb

Reverts Abdicoder123/african_queen_kitchen#14

Revert "Revert "generated order model""

---

db/migrate/20250117164226_create_orders.rb
db/schema.rb

I changed the total cost column to store cost as a decimal instead of an integer
[the ticket](https://trello.com/c/0sUL0ARe/60-change-totalcost-column)
- "Stripe handles monetary values in the smallest currency unit (e.g., cents for USD). Instead of storing $10.00 as 10.00, you typically store it as 1000 (integer, in cents). This avoids precision issues entirely."

changed total cost column

---

app/controllers/invoices_controller.rb
app/helpers/invoices_helper.rb
app/models/invoice.rb
app/views/invoices/_form.html.erb
app/views/invoices/_invoice.html.erb
app/views/invoices/_invoice.json.jbuilder
app/views/invoices/edit.html.erb
app/views/invoices/index.html.erb
app/views/invoices/index.json.jbuilder
app/views/invoices/new.html.erb
app/views/invoices/show.html.erb
app/views/invoices/show.json.jbuilder
config/routes.rb
db/migrate/20250118004846_create_invoices.rb
db/schema.rb
test/controllers/invoices_controller_test.rb
test/fixtures/invoices.yml
test/models/invoice_test.rb
test/system/invoices_test.rb

Used scaffold to create the controller, view, and db migrations for invoice model.
- Created invoice controller
- Created invoice view
- Created invoice migrations
- Added order reference to invoice model
- Run rails db:migrate

Generate invoice model

---

app/models/dish.rb
db/migrate/20250120155944_create_dishes.rb
db/schema.rb
test/fixtures/dishes.yml
test/models/dish_test.rb

- Created the dish model menu with the necessary columns.

Created dish model and made it belong to menu

---

app/models/dish.rb
app/models/order.rb
db/migrate/20250121165559_rename_order_items_to_order_dishes.rb
db/schema.rb

- I changed the order_item model to be called order_dishes to follow proper guidelines. the [ticket](https://trello.com/c/YLTUDOUW/68-debug-change-orderitem-to-orderdishes)
- Generated a migration to rename the order_item model to be called order_dishes
- Updated associations with old name to new name
- Run db:migrate

Debug: changed order_items to order_dishes

---

app/models/review.rb
db/migrate/20250121174923_create_reviews.rb
db/schema.rb
test/fixtures/reviews.yml
test/models/review_test.rb

- Generating the review model and made sure it belonged to the dish and user model.  Here's the ticket: https://trello.com/c/jG2HtsUc

Feature generate review model

---

app/controllers/menus_controller.rb
app/helpers/menus_helper.rb
app/views/layouts/_nav.html.erb
app/views/menus/index.html.erb
app/views/menus/show.html.erb
config/routes.rb
test/controllers/menus_controller_test.rb

- I generated the menu controller/views
- Menu controller and index/show views
- Updated routes

Feature created menu controller and views

---

app/admin/dashboard.rb
app/admin/dishes.rb
app/admin/menus.rb
app/admin/orders.rb
app/models/order.rb

- I added order to the admin dashboard so the admin could change the status of orders. The [ticket](https://trello.com/c/uXgRbqHZ/27-add-crud-for-order-model-so-admins-can-manage-the-status)
- Added a dashboard for admin to view
- Cleaned up extra comments in admin files

Feature Added admin order to dashboard

---

app/controllers/reviews_controller.rb
app/javascript/application.js
app/models/order.rb
app/views/layouts/application.html.erb
app/views/reviews/_form.html.erb
app/views/reviews/index.html.erb
app/views/reviews/show.html.erb
config/importmap.rb

- Did the styling for review. Fixed the bugs for review.

Feature fix review bug styling

---

app/models/order.rb
db/seeds.rb

- I added in the supporting seed data with the menu and dish information we got. the [ticket](https://trello.com/c/hOIQt9DA/85-add-seed-file-data)
- Added seed data for menus and dishes.
- Be sure to run db:seed
- If db:seed is aborted check the orders section of seed file and change user id to a user id in your database

Support add seed data

---

app/admin/orders.rb
app/controllers/orders_controller.rb
app/services/create_checkout_service.rb
app/services/stripe_checkout_service.rb
app/views/orders/show.html.erb
config/routes.rb
db/migrate/20250125235342_add_stripe_checkout_session_id_to_invoices.rb
db/schema.rb

- Attached the stripe checkout system into the app. Users can pay for orders by viewing their orders in the app.
- Made a migration file to add stripe_checkout_id to invoices
- Created a stripe checkout service file to create a checkout for orders that have been accepted by the admin
- Added a button to the orders show page if the order is ready to accept payment 
- Update the status of invoice and order model
- run rails db:migrate
- Create a new order as a user 
- Accept the order as an admin 
- Go back to find order as a user and click show order
- Click pay now to lead to the check out and pay
- Check database to see if the status of invoice and order models were updated

Feature stripe checkout

---

db/migrate/20250126170717_change_price_to_decimal_in_dishes.rb
db/migrate/20250126222933_change_total_cost_to_decimal_in_orders.rb
db/schema.rb

- I changed the price column in dishes to take in decimals instead of integers because it wasn't getting stored properly.
The [ticket](https://trello.com/c/hC1E4mJW/89-bug-fix-seed-prices).
- Generated 2 new migrations to change integer to decimal for menu total price and dish price
- Be sure to run db:migrate and db:seed to see prices stored correctly

Bug Changed dish price to decimal instead of integer

---

app/admin/dashboard.rb
app/admin/orders.rb
app/controllers/orders_controller.rb
app/models/invoice.rb
app/models/order.rb
app/models/payment.rb
app/services/create_invoice_service.rb
app/services/stripe_checkout_service.rb
db/seeds.rb

- Once the user pays the invoice, the status for order, invoice, and payment will be updated to Paid/Complete.
- Added logic into the order controller under index to catch when user has paid the invoice

Feature: save to payment model

---

app/admin/admin_users.rb
app/admin/dashboard.rb
app/admin/dishes.rb
app/admin/invoices.rb
app/admin/menus.rb
app/admin/orders.rb

- I updated the active admin dashboards of menu, dish, invoices and orders.
The [ticket](https://trello.com/c/21i2ooMb/91-clean-up-active-admin-dashboard)
- I added overview information panels on each dashboard to be more explanatory for active admin

Feature update active admin dashboard

---

app/assets/stylesheets/menu.scss
app/views/menus/index.html.erb
app/views/menus/show.html.erb
db/seeds.rb

- Styled the dishes to match the rest of the app styling wise.

Feature styling menu dishes

---

app/admin/invoices.rb

- Now amount due is displayed in the admin's view of invoices
- Amount due is displayed in the admin's index view
- In Active Admin, the invoice is now linked to the order to see details
- Updated info panel for invoices

Feature updated amount due column for invoices

---

app/assets/stylesheets/about.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/devise.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/menu.scss
app/assets/stylesheets/review.scss
app/views/home/index.html.erb
app/views/layouts/_footer.html.erb
app/views/menus/_menu.html.erb
app/views/reviews/index.html.erb
app/views/reviews/new.html.erb

- Updated the overall site to have consistent colors
- Put 'About Us' first on the home page
- Overall colors match
- Got rid of the unwanted text that appeared on every menu
- Updated the contact info to be most up-to-date with the client
- Removed repeated body styling and condensed down to one
- Updated prices of each dish on the menu to have 2 decimal places

Feature updated overall site color

---

app/assets/stylesheets/order.scss
app/views/menus/_menu.html.erb
app/views/orders/_dish.html.erb
app/views/orders/_form.html.erb
app/views/orders/show.html.erb

- Fixed styling issues in all order pages.
- " Pay now " should open a new tab 
- Prices in order pages are displayed using money format
- Repositioned the alert messages to under the header 
- Added email to alert message when orders are cancelled.
- Added images under the section "Dishes in this order"

Feature update order
